name: carl
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pylint
  - rope
  - torchvision
  - cudatoolkit=11.3
  - torchaudio
  - pytorch
  - pybox2d
  - pip
  - pip:
      - gym
      - scipy
      - ConfigArgParse
      - numpy
      - pandas
      - xvfbwrapper
      - matplotlib
      - optuna
      - dataclasses
      - numpyencoder
      - pyglet
      - pytablewriter
      - PyYAML
      - tabulate
      - brax
      - protobuf
      - RNA
      - Pillow
      - py4j
      - ray
      - seaborn
      - stable_baselines3
      - sb3_contrib
      - pytest
      - debugpy
      - hydra-core
      - hydra-submitit-launcher
      - coax