encoder:
  outdir: './tmp/Encoder_Outputs'
  context_dataset: './database/Pendulum/new_60k.npy'
  model: ContextAE
  input_dim: 5
  latent_dim: 2
  hidden_dim: [3]
  epochs: 100
  val_epochs: 10
  split: 0.8
  M_N: 0.005

hyperband:
  real:
    rate:
      begin: 0.001
      end: 0.5
      prior: 'uniform'
    decay:
      begin: 1e-16
      end: 1e-4
      prior: 'uniform'
  integer:
    batch:
      begin: 30
      end: 128
      prior: 'log-uniform'
  search_config:
    max_resource: 14
    eta: 3
  seed: 42

  